#!/bin/bash

set -o errexit

javaDir="/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Commands"

currentDir=$(pwd)
buildDir=$currentDir/builddir

rm -rf $buildDir
mkdir -p $buildDir/src/mlflex
mkdir -p $buildDir/lib

cd /Users/srp33/Dropbox/Eclipse/mlflex/src/mlflex
for f in $(find . -depth -type f -name '*.java')
do
  d=$(dirname $f)

  mkdir -pv $buildDir/src/mlflex/$d
  cp -rvp $f $buildDir/src/mlflex/$d/$(basename $f)
done

cd $currentDir

cp -v lib/*.jar $buildDir/lib/
cp -v scripts/build.xml $buildDir

cd $buildDir

find src -name *.java > sources_list.txt
$javaDir/javac -Djava.ext.dirs=lib @sources_list.txt

#if [ "$1" != "NO" ]
#then
#  mkdir docs
#  $javaDir/javadoc -protected -splitindex -author -version -nodeprecated -extdirs lib -d docs @sources_list.txt -sourcepath src
#fi

rm sources_list.txt

ant

rm build.xml

echo `date +%m-%d-%Y-%H-%M` > Version.txt

mkdir -p ../release
rm -rf ../release/*

cp -v mlflex.jar ../release/
cp -v Version.txt ../release/

#if [ "$1" != "NO" ]
#then
#  cp -r docs ../release/
#fi

cp -r lib ../release/

cd ..
rm -rf $buildDir
rm -rf src
